### ISSUE TITLE
about.md: any XMPP account you're willing to share? /eom

### ISSUE THREAD

**Issue by TwizzyDizzy** [ffrank/ffrank.github.io#3]

**Comment by ffrank** [comment]
You probably noticed I haven't even gotten around to joining your Mattermost team.

I've recently grown wary of chatty channels, especially in a personal capacity. So, probably not going towards XMPP anytime soon, either.

**Comment by TwizzyDizzy** [comment]
Yeah well... I've mostly given up on the topic of pulling others into my accepted communication tools. The reality of messenger fragmentation is bad... yet good at the same time in terms of diversity.

For now, I'm usually falling back to mail. signed but unencrypted. sad story.
